"""Typed, validated domain models.

These Pydantic models are the contract between the CLI, the agents and the
orchestrator. Using them (instead of passing raw ``dict`` objects around) means
malformed input is rejected at the boundary and every downstream consumer gets
strongly-typed, already-validated data.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, StringConstraints, field_validator

# A string that is trimmed of surrounding whitespace and must not be empty.
NonEmptyStr = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1)]

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def slugify(value: str, *, max_length: int = 60) -> str:
    """Convert an arbitrary string into a filesystem-safe slug."""
    slug = _SLUG_RE.sub("-", value.strip().lower()).strip("-")
    slug = slug[:max_length].strip("-")
    return slug or "campaign"


class CampaignBrief(BaseModel):
    """The user-supplied input that drives a campaign generation run."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    product_name: NonEmptyStr
    product_description: NonEmptyStr
    target_audience: NonEmptyStr
    goal: NonEmptyStr
    tone: NonEmptyStr
    channels: list[str] = Field(min_length=1)

    @field_validator("channels", mode="before")
    @classmethod
    def _coerce_channels(cls, value: object) -> list[str]:
        """Accept a list or a comma-separated string; trim, drop blanks, dedupe."""
        if isinstance(value, str):
            items = value.split(",")
        elif isinstance(value, (list, tuple)):
            items = [str(item) for item in value]
        else:
            raise TypeError("channels must be a list of strings or a comma-separated string")

        seen: set[str] = set()
        cleaned: list[str] = []
        for item in items:
            normalised = item.strip()
            key = normalised.lower()
            if normalised and key not in seen:
                seen.add(key)
                cleaned.append(normalised)
        if not cleaned:
            raise ValueError("At least one non-empty channel is required.")
        return cleaned

    def as_prompt_context(self) -> str:
        """Render the brief as a bullet list for inclusion in an LLM prompt."""
        return (
            f"- Product name: {self.product_name}\n"
            f"- Product description: {self.product_description}\n"
            f"- Target audience: {self.target_audience}\n"
            f"- Goal: {self.goal}\n"
            f"- Tone: {self.tone}\n"
            f"- Channels: {', '.join(self.channels)}"
        )


class CopyContent(BaseModel):
    """Structured marketing copy produced by the copywriter agent."""

    model_config = ConfigDict(extra="ignore")

    tagline: NonEmptyStr
    primary_message: NonEmptyStr
    headlines: list[str] = Field(min_length=1)
    body_copy: NonEmptyStr
    call_to_action: NonEmptyStr

    @field_validator("headlines", mode="before")
    @classmethod
    def _coerce_headlines(cls, value: object) -> list[str]:
        """Accept either a single string or a list; keep only non-empty entries."""
        if isinstance(value, str):
            value = [value]
        if not isinstance(value, (list, tuple)):
            raise TypeError("headlines must be a string or list of strings")
        cleaned = [str(item).strip() for item in value if str(item).strip()]
        if not cleaned:
            raise ValueError("At least one non-empty headline is required.")
        return cleaned


class CampaignResult(BaseModel):
    """The complete output of a single campaign generation run."""

    model_config = ConfigDict(extra="forbid")

    brief: CampaignBrief
    research_summary: str
    marketing_copy: CopyContent
    image_prompts: list[str]
    final_brief: str
    model: str
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    duration_seconds: float = 0.0

    def to_markdown(self) -> str:
        """Render a self-contained Markdown document for archival/sharing."""
        headlines = "\n".join(f"- {h}" for h in self.marketing_copy.headlines) or "- (none)"
        prompts = (
            "\n".join(f"{i}. {p}" for i, p in enumerate(self.image_prompts, start=1))
            or "_(none generated)_"
        )
        generated = self.generated_at.strftime("%Y-%m-%d %H:%M:%S UTC")
        return (
            f"# Campaign Brief - {self.brief.product_name}\n\n"
            f"> Generated by Campaign Forge using `{self.model}` on {generated} "
            f"in {self.duration_seconds:.1f}s.\n\n"
            f"{self.final_brief.strip()}\n\n"
            "---\n\n"
            "## Appendix A - Research Summary\n\n"
            f"{self.research_summary.strip()}\n\n"
            "## Appendix B - Copy\n\n"
            f"**Tagline:** {self.marketing_copy.tagline}\n\n"
            f"**Primary message:** {self.marketing_copy.primary_message}\n\n"
            f"**Headlines:**\n{headlines}\n\n"
            f"**Body copy:**\n\n{self.marketing_copy.body_copy}\n\n"
            f"**Call to action:** {self.marketing_copy.call_to_action}\n\n"
            "## Appendix C - Image Prompts\n\n"
            f"{prompts}\n"
        )

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serialisable representation of the result."""
        return self.model_dump(mode="json")

    def save(self, output_dir: Path) -> Path:
        """Persist the result as ``.md`` and ``.json`` files.

        Args:
            output_dir: Directory to write into (created if necessary).

        Returns:
            Path to the written Markdown file.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        stamp = self.generated_at.strftime("%Y%m%d-%H%M%S")
        base = output_dir / f"{stamp}_{slugify(self.brief.product_name)}"
        md_path = base.with_suffix(".md")
        json_path = base.with_suffix(".json")
        md_path.write_text(self.to_markdown(), encoding="utf-8")
        json_path.write_text(self.model_dump_json(indent=2), encoding="utf-8")
        return md_path
